# Generated by Django 4.2.6 on 2023-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Empresa')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Empresas',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('empresa', models.IntegerField(blank=True, null=True, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'UsuarioSistema',
                'verbose_name_plural': 'Usuario_Sistema',
                'db_table': 'usuarioSistema',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
    ]
