# Generated by Django 4.2.6 on 2023-10-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': True, 'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.empresa'),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
    ]
