# Generated by Django 4.2.6 on 2023-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Empresa'),
        ),
    ]
